query GetAllSelectedPracticeBase(
  $studentName: String
  $studentGroup: String
  $pharmacyName: String
  $pharmacyCity: String
  $pharmacyAddress: String
  $currentPage: Int = 1
  $pageSize: Int = 10
) {
  selectedBasesOfPractices(
    pagination: { page: $currentPage, pageSize: $pageSize }
    filters: {
      student: { name: { contains: $studentName }, group: { name: { eq: $studentGroup } } }
      pharmacy: {
        name: { contains: $pharmacyName }
        city: { contains: $pharmacyCity }
        address: { contains: $pharmacyAddress }
      }
    }
  ) {
    meta {
      pagination {
        total
        page
        pageSize
        pageCount
      }
    }

    data {
      id
      attributes {
        student {
          data {
            id
            attributes {
              name
              group {
                data {
                  id
                  attributes {
                    name
                    courseNumber
                  }
                }
              }
              phone
              middleName
            }
          }
        }
        pharmacy {
          data {
            id
            attributes {
              name
              city
              number
              address
              legalName
              contractNumber
              headOfPractice
            }
          }
        }
      }
    }
  }
}
