query GetAllStudents {
  students {
    data {
      attributes {
        email
        name
        group {
          data {
            attributes {
              name
              courseNumber
            }
          }
        }
        access
        picture
        phone
      }
    }
  }
}
