query GetAllPharmacies {
  pharmacies(pagination: { pageSize: 5000 }, filters: { places: { notIn: 0 } }) {
    data {
      id
      attributes {
        name
        city
        address
        places
        legalName
        number
      }
    }
  }
}
