query GetAllPharmacies($currentPage: Int = 1, $pageSize: Int = 10) {
  pharmacies(
    pagination: { page: $currentPage, pageSize: $pageSize }
    filters: { places: { notIn: 0 } }
  ) {
    meta {
      pagination {
        total
        page
        pageSize
        pageCount
      }
    }

    data {
      id
      attributes {
        name
        city
        address
        places
        legalName
        number
      }
    }
  }
}
