query GetAllPharmacies {
  pharmacies(pagination: { pageSize: 5000 }) {
    data {
      id
      attributes {
        name
        city
        address
        places
        brand
        number
      }
    }
  }
}
