query GetFullPharmacy($id: ID!) {
  pharmacies(filters: { id: { contains: $id } }) {
    data {
      id
      attributes {
        name
        city
        address
        places
        contractNumber
        legalName
        number
      }
    }
  }
}
