query GetSelectedPracticeCountById($pharmacyId: ID!) {
  selectedBasesOfPractices(filters: { pharmacy: { id: { eq: $pharmacyId } } }) {
    data {
      attributes {
        pharmacy {
          data {
            id
          }
        }
      }
    }
  }
}
